<?php require('req_global.php') ;
$page1 = mysqli_query($conn, "SELECT * FROM webpage WHERE pageID = 1");
$page2 = mysqli_query($conn, "SELECT * FROM webpage WHERE pageID = 2");
$page3 = mysqli_query($conn, "SELECT * FROM webpage WHERE pageID = 3");
$page4 = mysqli_query($conn, "SELECT * FROM webpage WHERE pageID = 4");
$page5 = mysqli_query($conn, "SELECT * FROM webpage WHERE pageID = 5");

$page_row1 = mysqli_fetch_assoc($page1);
$page_row2 = mysqli_fetch_assoc($page2);
$page_row3 = mysqli_fetch_assoc($page3);
$page_row4 = mysqli_fetch_assoc($page4);
$page_row5 = mysqli_fetch_assoc($page5);

$feedback = array();
$items = '';
$location = '';
$pageID = '';
if (isset($_POST['pageID'])) {
	// $feedback[] = 'You used the insert form.';
	// convert to our standard variables
	$pageID = $_POST['pageID'];
	// required fields
	if (count ($feedback) == 0)
	{
		$delete_sql = "
		DELETE FROM info
		WHERE pageID = " . $pageID ."
		";
		if (!mysqli_query($conn, $delete_sql))
		{
			// problem inserting
			$feedback[] = "Error description: " . mysqli_error($conn);
		} 
		else
		{
			// send 'em to the manage page.
			header('Location:find_page1.php?');
			exit();
		}
	}
}
$pageID = 1;
if(isset($_GET['pageID']))
{
	$pageID = $_GET['pageID'];
}
if(isset($_POST['pageID']))
{
	$pageID = $_POST['pageID'];
}
$sql = "SELECT * FROM info WHERE pageID =" . $pageID;
$result = mysqli_query($conn, $sql);
$item = mysqli_fetch_assoc($result);
$pageID = $item ['pageID'];
$items = $item ['item'];
$location = $item ['location'];
 ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<meta name="description" content="An Icon Font Generated By IcoMoon.io">
	<meta name="viewport" content="width=device-width">
	<title><?php echo $page_row4['mmTitle']; ?></title>
	
	<!-- <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"> -->
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" type="text/css" href="css/icomoon35944/style.css">
</head>
<body>
	<section>
		<form action="delete.php" method="post">
					<input type="hidden" name="pageID" value="<?php echo $pageID; ?>">
					
					<table border="1" cellpadding="5" cellspacing="0" width="50%">';
						<tr>
							<!-- <td><?php echo $pageID; ?></td> -->
							<td><?php echo $items; ?></td>
							<td><?php echo $location; ?></td>
						</tr>
						
					</table>
		
					<div class="row">
						<input type="submit" value="Delete">
					</div>
					
				</form>
		<div class="bottomLine">
			<a href="<?php echo $page_row5['mmLink']; ?>">
				<div class="glyph fs1">
					<div class="clearfix bshadow0 pbs">
						<span class="icon-arrow"></span>
					</div>
				</div>
			</a>
		<!-- <a href="second_page.html"> -->
				<div class="glyph fs1">
					<div class="clearfix bshadow0 pbs">
						<span class="icon-jclogo"></span>
					</div>
				</div>
			<!-- </a> -->
			<!-- <a href="second_page.html"> -->
				<div class="glyph fs1">
					<div class="clearfix bshadow0 pbs">
						<span class="icon-exit"></span>
					</div>
				</div>
			<!-- </a> -->
		</div>
	</section>			
</body>
<script src="scripts/jquery.min.js" type="text/javascript"></script>
<script src="scripts/jquery-2.1.0.js" type="text/javascript"></script>
    <script src="scripts/jquery.backgroundpos.min.js" type="text/javascript"></script>
<script type="text/javascript">
 
 </script>
</html>